version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: edopla_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - DEBUG=${DEBUG}
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    container_name: edopla_backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - ENV=${ENV}
      - DEBUG=${DEBUG}
